# llm_service/main.py
from fastapi import FastAPI
from pydantic import BaseModel
import random

app = FastAPI(title="LLM Service")

class LLMRequest(BaseModel):
    text: str
    clo: str
    bloom_level: str
    assessment_type: str
    num_questions: int = 3

@app.post("/generate")
def generate_assessment(req: LLMRequest):
    """
    Mock version of LLM generation.
    Later you can integrate an OpenAI or HuggingFace model here.
    """
    questions = []
    for i in range(req.num_questions):
        questions.append({
            "question": f"Q{i+1}: Based on {req.clo} and Bloom {req.bloom_level}, what is ...?",
            "answer": "Sample answer generated by LLM.",
            "rubric": {
                "Excellent": "Thorough and well-reasoned response.",
                "Average": "Basic understanding with some gaps.",
                "Poor": "Minimal or incorrect explanation."
            }
        })
    return {
        "job_id": f"job_{random.randint(1000,9999)}",
        "questions": questions
    }
