# Generated by Django 5.2.6 on 2026-02-17 21:14

import assessment_marking.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradedSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Assessment Grading', max_length=255)),
                ('student_file', models.FileField(upload_to=assessment_marking.models.grading_upload_to)),
                ('rubric_file', models.FileField(upload_to=assessment_marking.models.grading_upload_to)),
                ('ai_result_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
