# Generated by Django 5.2.6 on 2026-01-25 11:20

import assessment_marking.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_management', '0002_alter_clo_unique_together_clo_bloom_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradedSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Assessment Grading', max_length=255)),
                ('student_file', models.FileField(upload_to=assessment_marking.models.grading_upload_to)),
                ('rubric_file', models.FileField(upload_to=assessment_marking.models.grading_upload_to)),
                ('ai_result_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_management.course')),
            ],
        ),
    ]
