# Generated by Django 5.2.6 on 2026-02-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_marking', '0001_initial'),
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedsubmission',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_management.course'),
        ),
    ]
