# Generated by Django 5.2.6 on 2025-10-18 09:16

import assessment_creation.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clo', models.CharField(max_length=512)),
                ('bloom_level', models.CharField(max_length=50)),
                ('assessment_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=assessment_creation.models.assessment_upload_to)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessment_creation.lecturematerial')),
            ],
        ),
    ]
