# Generated by Django 5.2.8 on 2026-02-22 07:28

import assessment_creation.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(max_length=50)),
                ('questions_config', models.JSONField(blank=True, default=list)),
                ('clo', models.CharField(blank=True, max_length=512, null=True)),
                ('bloom_level', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=assessment_creation.models.assessment_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
