# Generated by Django 5.2.6 on 2025-12-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='questions_config',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='bloom_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='clo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
