# Generated by Django 5.2.8 on 2026-02-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_creation', '0001_initial'),
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='course_management.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessment_creation.lecturematerial'),
        ),
    ]
