# Generated by Django 5.2.6 on 2025-12-16 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_creation', '0002_assessment_questions_config_and_more'),
        ('course_management', '0002_alter_clo_unique_together_clo_bloom_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='course_management.course'),
        ),
    ]
